### ISSUE TITLE
Despliegue a servidor público

### ISSUE THREAD

**Issue by srojascaballero** [ISWPOLI/AntaraIngenieriaSoftwareII#1]

**Comment by srojascaballero** [comment]
En progreso.

**Comment by jsperezp** [comment]
El despliegue a servidor publico se indico al profesor que por politicas de seguridad el banco no seria posible realizarlo y como contingtencia se propuso presentar una conexion remota para mostrar el despliegue. Considero que deberiamos cerrar esta Issue de acuerdo a estas condiciones.

**Comment by srojascaballero** [comment]
con base en la respuesta que se le día al profesor, se cierra esta issue.
