### ISSUE TITLE
Plan de pruebas

### ISSUE THREAD

**Issue by srojascaballero** [ISWPOLI/AntaraIngenieriaSoftwareII#10]

**Comment by aacasallas** [comment]
[plan de pruebas funcional Antara.xlsx](https://github.com/ISWPOLI/AntaraIngenieriaSoftwareII/files/537899/plan.de.pruebas.funcional.Antara.xlsx)

**Comment by jdjinete** [comment]
Se realiza plan de pruebas en base al análisis realizado a la matriz de riesgo  @aacasallas  por favor comentar y cerrar esta acitvidad

**Comment by aacasallas** [comment]
Se completa acciones para mitigacion de riesogs
