### ISSUE TITLE
Modelado de negocio (Canvas)

### ISSUE THREAD

**Issue by srojascaballero** [ISWPOLI/AntaraIngenieriaSoftwareII#17]

**Comment by aacasallas** [comment]
![canvas](https://cloud.githubusercontent.com/assets/22159470/19586061/3c080430-9717-11e6-83f6-9db3acb18e06.jpg)

**Comment by aacasallas** [comment]
Se adjunta modelo canvas con la información del banco BBVA, para el proyecto de ingeniería de sotware 2
