### ISSUE TITLE
Perfilado de equipo de trabajo

### ISSUE THREAD

**Issue by srojascaballero** [ISWPOLI/AntaraIngenieriaSoftwareII#20]

**Comment by jdjinete** [comment]
Lo roles se encuentran especificados en la ERS y en la presentaciòn de ingeniria software realizada en el mes de agosto en clase.
Sebastian Rojas: Desarrollador
Alvaro Casallas: Analista.
Jhonatan Perez: Analista
David Jinete: Scrum Master.
