### ISSUE TITLE
Selección de metodologia 

### ISSUE THREAD

**Issue by srojascaballero** [ISWPOLI/AntaraIngenieriaSoftwareII#24]

**Comment by jdjinete** [comment]
Scrum

Para este proyecto se decide tomar como metodología de desarrollo, metodología ágil SCRUM ya que es estamos hablando de un equipo pequeño, la poca necesidad de la documentación (solamente lo necesario e importante) teniendo en cuenta avance con respecto a entregas rápidas, y ademas que es un proyecto susceptible a modificaciones  a mitad del ciclo del desarrollo.
