### ISSUE TITLE
Diagrama de infraestructura

### ISSUE THREAD

**Issue by srojascaballero** [ISWPOLI/AntaraIngenieriaSoftwareII#30]

**Comment by jdjinete** [comment]
Se finaliza con éxito el diagrama de infraestructura y se anexa a la presentación del proyecto.
[https://docs.google.com/presentation/d/1iOfZH01eowrBnRR1zaIbBJLavy_oV-LHXAYDvPlgsRY/edit#slide=id.g18d7739597_1_42](url)

**Comment by alejandro995** [comment]
No se puede ver el diagrama, saludos
